# Generated by Django 5.1.6 on 2025-03-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("description", models.TextField()),
                ("organizer_contact", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("timings", models.CharField(blank=True, max_length=255, null=True)),
                ("ratings", models.FloatField(default=0.0)),
            ],
        ),
    ]
